name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: g++ -Wall -Wextra -o testchecker main.cpp ColorPair.cpp ColorMapper.cpp ReferenceManual.cpp
      
    - name: run
      run: ./testchecker
